
FROM openjdk:17-jdk-slim

ENV WORKDIR=/app

WORKDIR $WORKDIR

COPY target/spring-petclinic*.jar app.jar


RUN apt-get update && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080

ENTRYPOINT [ "java" ,"-jar" , "app.jar" ]