pipeline {
    agent any
   
    }
    
    stages {
        stage('Debug') {
            steps {
                script {
                    sh '''
                    echo "Current Directory: $(pwd)"
                    echo "Listing files:"
                    ls -la
                    '''
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building Spring Pet Clinic app...'
                script {
                    sh '''
                    docker-compose -f ./Task10/docker-compose.yml up -d
                    '''
                }
            }
        }
        
        stage('Test') {
            steps {
              
                script {
                    sh '''
                    docker ps | grep sp_app || (echo "App container not found" && exit 1)
                    docker ps | grep db || (echo "DB container not found" && exit 1)
                    '''
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Application is running in Docker containers.'
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed!'
        }
        
        success {
            echo 'Pipeline succeeded! Application deployed successfully.'
            echo "Access the app at http://localhost:3002"
        }
        
        failure {
            echo 'Pipeline failed! Check logs for errors.'
            script {
                sh 'docker-compose logs --tail=20'
            }
        }
    }
}
