pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                dir('Task10') {
                    echo 'Building the Spring Petclinic application will be done using Docker Compose...'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('Task10') {
                    echo 'Check if the Spring Petclinic application files is available...'
                    
                    sh 'if [ -f docker-compose.yml ]; then echo "docker-compose.yml exists"; else echo "docker-compose.yml is missing"; exit 1; fi'
                    sh 'if [ -f Dockerfile ]; then echo "Dockerfile exists"; else echo "Dockerfile is missing"; exit 1; fi'
                    echo 'All necessary files are present.'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                dir('Task10') {
                    echo 'Deploying the Spring Petclinic application...'
                    
                    sh 'docker-compose -f docker-compose.yml up -d --build'
                    sleep 30  
                    sh 'docker-compose ps'
                    
                    echo 'Application deployed successfully!'
                    echo 'Access the app at: http://localhost:3002'
                }
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline completed successfully!'
            echo 'you can access the app at: http://localhost:3002'
        }
        failure {
            echo 'Pipeline failed! Check the logs'
        }
    }
}