# docker-compose file for Spring Petclinic application with MySQL database
# 
#
services:
  database:

    image: mysql

    container_name: database

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic

    networks:
      - petclinic-net

    volumes:
      - ./db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 15s
      timeout: 5s
      retries: 3
  petclinic-app:

    image: mhmdocker1/spring-petclinic:latest
  
    container_name: spring-petclinic-app
  
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
  
    ports:
      - 3002:8080
  
    networks:
      - petclinic-net
  
    depends_on:
      database:  
        condition: service_healthy
           
networks:
  petclinic-net:
    name: petclinic-net
    driver: bridge