name: Deploy Monitoring Services
on:
  push:
    paths:
      - 'Task12/docker-compose-monitoring.yml'
      - 'Task12/prometheus.yml'
    branches:
      - main  
  workflow_dispatch:  
jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    
    steps:

  
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check file changes
      id: check_changes
      run: |
        echo "File change detected..."
        
    - name: Debug
      run: |
        echo "Listing workspace contents..."
        ls -la Task12
        
  
    - name: Down existing containers
      run: |
        echo "Stopping and removing existing containers..."
        docker compose -f Task12/docker-compose-monitoring.yml down || true
        
    - name: Run monitoring applications
      run: |
        echo "Running monitoring apps using docker-compose..."
        docker compose -f Task12/docker-compose-monitoring.yml up -d
        
    - name: Notify Slack on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: jenkins-monitoring
        SLACK_COLOR: good
        SLACK_MESSAGE: |
          Monitoring Applications are running 
          Commit: ${{ github.sha }}
          Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        
    - name: Notify Slack on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: jenkins-monitoring
        SLACK_COLOR: danger
        SLACK_MESSAGE: |
          Monitoring Applications Failed to run.
          Commit: ${{ github.sha }}
          Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
