name: Deploy Petclinic and Monitoring Services
on:
  push: 
    paths:
      - 'Task12/docker-compose-app,db.yml'
      - 'Task12/docker-compose-monitoring.yml'
      - 'Task12/prometheus.yml'
    branches:
      - main  
  workflow_dispatch:  

jobs:

  Debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check file changes
      id: check_changes
      run: |
        echo "File change detected..."
        
    - name: Debug
      run: |
        echo "Listing workspace contents..."
        ls -la Task12 

  deploy-petclinic:
    runs-on: ubuntu-latest
    needs: Debug

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Down existing containers
      run: |
        echo "Stopping and removing existing containers..."
        docker compose -f Task12/docker-compose-app,db.yml down || true
        
    - name: Run Spring Petclinic application
      run: |
        echo "Running spring-petclinic application with Database using docker-compose..."
        docker compose -f Task12/docker-compose-app,db.yml up -d
        
    - name: Wait for services to be healthy
      run: |
        echo "Waiting for services to start..."
        sleep 30
        docker compose -f Task12/docker-compose-app,db.yml ps
        
    - name: Notify Slack on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: github_action
        SLACK_COLOR: good
        SLACK_MESSAGE: |
          SpringPetclinic Application is running.
          Commit: ${{ github.sha }}
          Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        
    - name: Notify Slack on Failure
      if: failure() 
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: github_action
        SLACK_COLOR: danger
        SLACK_MESSAGE: |
          SpringPetclinic Application Failed to run.
          Commit: ${{ github.sha }}
          Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy-monitoring:
    runs-on: ubuntu-latest
    needs: Debug
    
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
  
    - name: Down existing containers
      run: |
        echo "Stopping and removing existing containers..."
        docker compose -f Task12/docker-compose-monitoring.yml down || true
        
    - name: Run monitoring applications
      run: |
        echo "Running monitoring apps using docker-compose..."
        docker compose -f Task12/docker-compose-monitoring.yml up -d
        
    - name: Notify Slack on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: github_action
        SLACK_COLOR: good
        SLACK_MESSAGE: |
          Monitoring Applications are running 
          Commit: ${{ github.sha }}
          Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        
    - name: Notify Slack on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: github_action
        SLACK_COLOR: danger
        SLACK_MESSAGE: |
          Monitoring Applications Failed to run.
          Commit: ${{ github.sha }}
          Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}


  